# generate_daily_brief.py
# v2.3 - Pametni daily brief sa spajanjem starog i novog

import datetime
today = datetime.date.today()
day_name = today.strftime("%A")
print("# ☀️ Dnevni brief — " + today.strftime("%d.%m.%Y.") + f" ({day_name})")
print("**Stellan v2.3** • Automatski generiran\n")
print("---\n")
print("## 🎯 Hitno danas (rok < 48h)\n")
print("\n\n---\n")
print("## 🔥 Najvažniji prioritet današnjeg dana\n")
print("Nastavak razvoja v2.3 + testiranje automatskih skripti\n")
print("\n---\n")
print("## 📬 Emailovi koji čekaju odgovor (>24h)\n")
print("\n---\n")
print("## 📊 SDGE — Promjene statusa aktivnih predmeta\n")
print("\n---\n")
print("## 💰 Financije / Solo (neplaćeno, otvorene ponude)\n")
print("\n---\n")
print("## 🧠 Status Mozga (v2.3)")
print("- memory.md — staro + novo spojeno (bez brisanja historije)")
print("- upute.md ažurirane")
print("- Pokrenuti daily brief, memory updater i weekly review\n")
print("## 🛠 Stellanov komentar i preporuka za danas")
print("Testiraj novi ZIP, commitaj, pa reci 'pokreni daily brief' ili 'pokreni weekly review'.")
print("\nSve je spremno za daljnje automate.")
